disabled_rules:
  - todo
  - opening_brace
  - cyclomatic_complexity
  - function_parameter_count
included:
  - Clipy
excluded:
  - Pods
  - Clipy/Libraries
line_length: 200
variable_name:
  excluded: 
    - SHORTEN_SYMBOL
