disabled_rules:
  - todo
  - opening_brace
  - cyclomatic_complexity
  - function_parameter_count
included:
  - Clipy
excluded:
  - Pods
  - Clipy/Libraries
line_length: 200
force_cast: warning
variable_name:
  excluded: 
    - SHORTEN_SYMBOL
    - ADD_SNIPPET_IDENTIFIER
    - DELETE_SNIPPET_IDENTIFIER
    - CHECK_SNIPPET_IDENTIFIER
    - DEFAULT_EXPORT_FILENAME
