language: objective-c
osx_image: xcode7.3
os: osx
install: 
  - bundle install --without development --deployment --jobs=3 --retry=3
  - bundle exec pod repo update --silent
script: travis_wait 30 'bundle exec fastlane test'
cache:
  - bundler
  - cocoapods
notifications:
  email: false
