language: objective-c
osx_image: xcode7.2
os: osx
script: bundle exec fastlane test
before_install:
  - bundle install --path=vendor/bundle --binstubs=vendor/bin
cache:
  directories:
    - vendor/bundle
    - Pods
notification:
  email: false
