language: objective-c
osx_image: xcode7.2
os: osx
install: bundle install --without development --deployment --jobs=3 --retry=3
script: bundle exec fastlane test
cache:
  directories:
    - vendor/bundle
    - Pods
notification:
  email: false
